### ISSUE TITLE
Support for Seeed HM3301 

### ISSUE THREAD

**Issue by sidikalamini** [adafruit/Adafruit_CircuitPython_PM25#22]
Suggest to include support for Grove PM2.5 HM3301

sample library here:-
https://github.com/SmartCowAi/jetson-nano-weather-station/blob/main/weather_station/seeed_hm3301.py

**Comment by ladyada** [comment]
hi! we don't own it so cannot add support ourselves. please submit a PR or ask Seeeed to submit support for it! :)

**Comment by sidikalamini** [comment]
ok, asking permission from the developer to submit PR here
