### ISSUE TITLE
Add explanation of "standard" and "environmental" sensor values to docs

### ISSUE THREAD

**Issue by psoberoi** [adafruit/Adafruit_CircuitPython_PM25#23]
The library returns two sets of concentrations: "standard" and "environmental" but the docs don't explain the difference between them. After some searching, I figured out that "standard" refers to what the concentration would be at standard pressure (i.e. sea level) whereas "environmental" refers to measured values that depend on ambient pressure. It would be nice to add this info to the docs.

(There's a discussion about this here: https://publiclab.org/questions/samr/04-07-2019/how-to-interpret-pms5003-sensor-values)

**Comment by ladyada** [comment]
ooh thats useful info!
@kattni plz add to learnguide / readme :)

**Comment by kattni** [comment]
Added to Learn guide: https://learn.adafruit.com/pm25-air-quality-sensor/usage-notes#standard-vs-environmental-concentration-3140491
